/**
 * The approved forms the export API is allowed to read.
 *
 * Built from a static manifest inside the Worker (worker/formAssets.js,
 * generated by scripts/build-form-manifest.mjs) and from disk in Node
 * scripts/tests (scripts/lib/nodeFormStore.mjs). Nothing outside these maps
 * is reachable — the maps ARE the allow-list, which is tighter than the old
 * directory scan. Callers never pass file paths, only keys.
 */
import { HttpError, assertSafeKey } from './_shared.js';

const own = (obj, key) => Object.prototype.hasOwnProperty.call(obj, key);

export function createFormStore({ fieldMaps = {}, basePdfs = {}, schemas = {} } = {}) {
  const templateKeys = new Set();
  for (const stem of Object.keys(fieldMaps)) {
    const m = stem.match(/^(.*)-(ed\d+)$/i);
    templateKeys.add(m ? m[1] : stem);
  }

  return {
    templateKeys,

    resolveFieldMap(templateKey, version = 'ed01') {
      const key = assertSafeKey(templateKey, 'templateKey');
      const ver = assertSafeKey(version, 'templateVersion');
      if (!templateKeys.has(key)) throw new HttpError(400, `Unknown templateKey: ${key}`);
      const stem = `${key}-${ver}`;
      if (!own(fieldMaps, stem)) throw new HttpError(400, `Field map not found for ${stem}`);
      return structuredClone(fieldMaps[stem]);
    },

    readApprovedBasePdf(fieldMap) {
      const name = assertSafeKey(fieldMap?.basePdf, 'basePdf');
      if (!own(basePdfs, name)) throw new HttpError(400, `Approved base PDF missing: ${name}`);
      const bytes = basePdfs[name];
      return bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
    },

    loadSchema(templateKey) {
      if (!templateKey || !own(schemas, templateKey)) return null;
      return structuredClone(schemas[templateKey]);
    },
  };
}
